# Generated by Django 3.2.7 on 2022-09-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
